# Generated by Django 3.0.8 on 2020-10-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0002_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('block_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumApp.Blocks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumApp.ForumUser')),
            ],
        ),
    ]
