# Generated by Django 3.0.8 on 2020-10-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0003_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(),
        ),
    ]
